"""se agrega columna Ciudad en Edificio

Revision ID: 485a6b2c0305
Revises: e7d8a54664b4
Create Date: 2026-01-09 19:27:38.118687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485a6b2c0305'
down_revision: Union[str, None] = 'e7d8a54664b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Edificio', sa.Column('Ciudad', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Edificio', 'Ciudad')
    # ### end Alembic commands ###
