"""se corrige de  nuevo  modelo tabla Enlace

Revision ID: 705c50bcf060
Revises: eefea6188bac
Create Date: 2026-01-09 19:37:51.505419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705c50bcf060'
down_revision: Union[str, None] = 'eefea6188bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Enlace', sa.Column('Referencia', sa.String(length=200), nullable=False))
    op.add_column('Enlace', sa.Column('EsDeTerceros', sa.Boolean(), nullable=False))
    op.drop_column('Enlace', 'EsDeRecurso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Enlace', sa.Column('EsDeRecurso', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Enlace', 'EsDeTerceros')
    op.drop_column('Enlace', 'Referencia')
    # ### end Alembic commands ###
