"""se hacen  nullables  Campos  en Tabla Edificio

Revision ID: 9968c95ed896
Revises: 425e44203be6
Create Date: 2026-01-09 19:32:22.814593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9968c95ed896'
down_revision: Union[str, None] = '425e44203be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Edificio', 'Responsable',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('Edificio', 'Telefono',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('Edificio', 'Fax',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('Edificio', 'Observaciones',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Edificio', 'Email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Edificio', 'Email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('Edificio', 'Observaciones',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('Edificio', 'Fax',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('Edificio', 'Telefono',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('Edificio', 'Responsable',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
