"""Initial migration

Revision ID: bf99a1445b3e
Revises: 
Create Date: 2026-01-07 15:53:14.202383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf99a1445b3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RazonSocial', sa.String(length=150), nullable=False),
    sa.Column('Activo', sa.String(length=20), nullable=True),
    sa.Column('FechaDeAlta', sa.Date(), nullable=True),
    sa.Column('FechaDeBaja', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Dominio',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Mantenedor',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Descripcion', sa.String(length=200), nullable=False),
    sa.Column('Contacto', sa.String(length=200), nullable=False),
    sa.Column('Direccion', sa.String(length=200), nullable=False),
    sa.Column('Telefono', sa.String(length=40), nullable=False),
    sa.Column('Fax', sa.String(length=40), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('OperadorRegistro',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Descripcion', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Proveedor',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Descripcion', sa.String(length=200), nullable=False),
    sa.Column('Contacto', sa.String(length=200), nullable=False),
    sa.Column('Direccion', sa.String(length=500), nullable=False),
    sa.Column('Telefono', sa.String(length=40), nullable=False),
    sa.Column('Fax', sa.String(length=40), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Provincia',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TipoEvento',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Descripcion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TipoIdentificador',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Descripcion', sa.String(length=100), nullable=False),
    sa.Column('Observaciones', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TipoObjeto',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ArchivosImportados',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClienteId', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('operador', sa.String(length=50), nullable=False),
    sa.Column('FileName', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['ClienteId'], ['Cliente.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Edificio',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClienteId', sa.Integer(), nullable=False),
    sa.Column('ProvinciaId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('Sucursal', sa.String(length=200), nullable=False),
    sa.Column('Direccion', sa.String(length=200), nullable=False),
    sa.Column('Codigo', sa.String(length=200), nullable=False),
    sa.Column('Responsable', sa.String(length=200), nullable=False),
    sa.Column('Telefono', sa.String(length=200), nullable=False),
    sa.Column('Fax', sa.String(length=200), nullable=False),
    sa.Column('Observaciones', sa.String(length=500), nullable=False),
    sa.Column('Email', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ClienteId'], ['Cliente.Id'], ),
    sa.ForeignKeyConstraint(['ProvinciaId'], ['Provincia.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('TipoEstadistica',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClienteId', sa.Integer(), nullable=False),
    sa.Column('Descripcion', sa.String(length=200), nullable=False),
    sa.Column('Observaciones', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['ClienteId'], ['Cliente.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Enlace',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EdificioId', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('EsDeRecurso', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['EdificioId'], ['Edificio.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Estadistica',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClienteId', sa.Integer(), nullable=False),
    sa.Column('DominioId', sa.Integer(), nullable=False),
    sa.Column('Desde', sa.DateTime(), nullable=False),
    sa.Column('Hasta', sa.DateTime(), nullable=False),
    sa.Column('TipoEstadisticaId', sa.Integer(), nullable=False),
    sa.Column('duracionExcluida', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ClienteId'], ['Cliente.Id'], ),
    sa.ForeignKeyConstraint(['DominioId'], ['Dominio.Id'], ),
    sa.ForeignKeyConstraint(['TipoEstadisticaId'], ['TipoEstadistica.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('DetalleEstadisticaPorEnlace',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EstadisticaId', sa.Integer(), nullable=False),
    sa.Column('EnlaceId', sa.Integer(), nullable=False),
    sa.Column('CantidadFallas', sa.Integer(), nullable=False),
    sa.Column('TMEF', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('Disponibilidad', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('TDP', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('TiempoConRespaldo', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('DisponibilidadConRespaldo', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['EnlaceId'], ['Enlace.Id'], ),
    sa.ForeignKeyConstraint(['EstadisticaId'], ['Estadistica.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('EnlaceDominio',
    sa.Column('EnlaceId', sa.Integer(), nullable=False),
    sa.Column('DominioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DominioId'], ['Dominio.Id'], ),
    sa.ForeignKeyConstraint(['EnlaceId'], ['Enlace.Id'], ),
    sa.PrimaryKeyConstraint('EnlaceId', 'DominioId')
    )
    op.create_table('Objeto',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TipoObjetoId', sa.Integer(), nullable=False),
    sa.Column('EnlaceId', sa.Integer(), nullable=False),
    sa.Column('Activo', sa.Boolean(), nullable=True),
    sa.Column('ProveedorId', sa.Integer(), nullable=False),
    sa.Column('MantenedorId', sa.Integer(), nullable=False),
    sa.Column('FechaAlta', sa.Date(), nullable=True),
    sa.Column('Observaciones', sa.String(length=500), nullable=True),
    sa.Column('ObjetoBackupId', sa.Integer(), nullable=True),
    sa.Column('SoloActuaComoBackup', sa.Boolean(), nullable=True),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['EnlaceId'], ['Enlace.Id'], ),
    sa.ForeignKeyConstraint(['MantenedorId'], ['Mantenedor.Id'], ),
    sa.ForeignKeyConstraint(['ObjetoBackupId'], ['Objeto.Id'], ),
    sa.ForeignKeyConstraint(['ProveedorId'], ['Proveedor.Id'], ),
    sa.ForeignKeyConstraint(['TipoObjetoId'], ['TipoObjeto.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('DetalleEstadistica',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EstadisticaId', sa.Integer(), nullable=False),
    sa.Column('CantidadFallas', sa.Integer(), nullable=False),
    sa.Column('PorcentajeDisponibilidad', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('TiempoMuerto', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('TiempoMuertoEntreFallas', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('TiempoMuertoDelRespaldo', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('PorcentajeDisponibilidadConRespaldo', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ObjetoId', sa.Integer(), nullable=False),
    sa.Column('EnlaceId', sa.Integer(), nullable=False),
    sa.Column('TDFNeto', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('TMEF', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('TMR', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('TDF', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['EnlaceId'], ['Enlace.Id'], ),
    sa.ForeignKeyConstraint(['EstadisticaId'], ['Estadistica.Id'], ),
    sa.ForeignKeyConstraint(['ObjetoId'], ['Objeto.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Evento',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ObjetoId', sa.Integer(), nullable=False),
    sa.Column('TipoEvento', sa.Integer(), nullable=False),
    sa.Column('OperadorRegistroId', sa.Integer(), nullable=False),
    sa.Column('Fecha', sa.DateTime(), nullable=False),
    sa.Column('Observaciones', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ObjetoId'], ['Objeto.Id'], ),
    sa.ForeignKeyConstraint(['OperadorRegistroId'], ['OperadorRegistro.Id'], ),
    sa.ForeignKeyConstraint(['TipoEvento'], ['TipoEvento.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('IdentificadorObjeto',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ObjetoId', sa.Integer(), nullable=False),
    sa.Column('TipoIdentificadorId', sa.Integer(), nullable=False),
    sa.Column('ValorIdentificador', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ObjetoId'], ['Objeto.Id'], ),
    sa.ForeignKeyConstraint(['TipoIdentificadorId'], ['TipoIdentificador.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('oep',
    sa.Column('ObjetoId', sa.Integer(), nullable=False),
    sa.Column('EnlaceId', sa.Integer(), nullable=False),
    sa.Column('ProveedorId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EnlaceId'], ['Enlace.Id'], ),
    sa.ForeignKeyConstraint(['ObjetoId'], ['Objeto.Id'], ),
    sa.ForeignKeyConstraint(['ProveedorId'], ['Proveedor.Id'], ),
    sa.PrimaryKeyConstraint('ObjetoId', 'EnlaceId', 'ProveedorId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oep')
    op.drop_table('IdentificadorObjeto')
    op.drop_table('Evento')
    op.drop_table('DetalleEstadistica')
    op.drop_table('Objeto')
    op.drop_table('EnlaceDominio')
    op.drop_table('DetalleEstadisticaPorEnlace')
    op.drop_table('Estadistica')
    op.drop_table('Enlace')
    op.drop_table('TipoEstadistica')
    op.drop_table('Edificio')
    op.drop_table('ArchivosImportados')
    op.drop_table('TipoObjeto')
    op.drop_table('TipoIdentificador')
    op.drop_table('TipoEvento')
    op.drop_table('Provincia')
    op.drop_table('Proveedor')
    op.drop_table('OperadorRegistro')
    op.drop_table('Mantenedor')
    op.drop_table('Dominio')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
