"""Columna Direccion de Edificio se cambia a NUllable

Revision ID: e7d8a54664b4
Revises: bf99a1445b3e
Create Date: 2026-01-09 19:24:39.151302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8a54664b4'
down_revision: Union[str, None] = 'bf99a1445b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Edificio', 'Direccion',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('Edificio', 'Ciudad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Edificio', sa.Column('Ciudad', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('Edificio', 'Direccion',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
